security:
    encoders:
        App\Entity\User:
            algorithm: auto
            
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/create/(city|place|review), roles: ROLE_USER }
        - { path: ^/edit/place, roles: ROLE_USER }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_USER: ROLE_USER